# -*- coding: utf-8 -*-
"""2021E075_Lab1_EC9630.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SeBQrJyjWlMZ5GF0bGfLtwIsYOxRah6e

# EC9630 Machine Learning - Laboratory 1

Task: STASTICAL PATTEN CLASSIFICATION – DECISION TREE AND INFORMATION GAIN

Name: Jayasinghe K.J.M.U.G.S.E.

Reg No: 2021/E/075

Date: 31/01/2025

Time: 1.30

1. Setup and Import Libraries
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from google.colab import files
uploaded = files.upload()

"""2. Loading the Dataset"""

df = pd.read_csv('diabetes_binary_health_indicators_BRFSS2015.csv')

"""3. data analysis"""

df.head()

df.tail()

print("Dataset Shape:", df.shape)
print("Column Names:", df.columns.tolist())
print("\nData Summary:\n")
print(df.info())

print(df.dtypes)

print(df.describe())

"""4. Data Visualization"""

# Checking for missing values
df.isnull().sum()

sns.scatterplot(x=df['Age'], y=df['Diabetes_binary'])

df1 = df.set_index("Age")
df1.head()

sns.histplot(df1.index, bins=20, kde=True)
plt.xlabel("Age")
plt.ylabel("Frequency")
plt.title("Age Distribution")
plt.show()

print(df['Diabetes_binary'].value_counts())

# Box plot for Age vs. Class
sns.boxplot(x='Diabetes_binary', y='Age', data=df)
plt.title('Age Distribution by Class')
plt.show()

df.hist(figsize=(12, 8))
plt.show()

"""5. Data Preprocessing"""

categorical_cols = df.select_dtypes(include=['object']).columns
df_encoded = pd.get_dummies(df, columns=categorical_cols)

print(df.head())

"""6. Feature Selection"""

from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()

for column in df.columns:
    if df[column].dtype == 'object':
        df[column] = label_encoder.fit_transform(df[column])

X = df.drop('Diabetes_binary', axis=1)
y = df['Diabetes_binary']

print("Features:", X.columns.tolist())

# Correlation Analysis
plt.figure(figsize=(12, 8))
sns.heatmap(df.corr(), annot=True, cmap='coolwarm')
plt.title('Correlation Matrix')
plt.show()

X_encoded = pd.get_dummies(X)

print(X_encoded.head())

print("Shape of Features:", X.shape)
print("Shape of Labels:", y.shape)

"""7. Splitting the Data"""

#Feature Selection using Information Gain
from sklearn.feature_selection import mutual_info_classif

info_gain = mutual_info_classif(X_encoded, y, random_state=42)
info_gain = pd.Series(info_gain, index=X_encoded.columns)
info_gain = info_gain.sort_values(ascending=False)

print(info_gain)

# Plot information gain values
plt.figure(figsize=(10,6))
info_gain.plot(kind='bar')
plt.title('Information Gain for Each Feature')
plt.xlabel('Features')
plt.ylabel('Information Gain')
plt.xticks(rotation=45)
plt.show()

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X_encoded)

#Splitting the Data
from sklearn.model_selection import train_test_split
# Split data into training (70%) and temporary set (30%)
X_train, X_temp, y_train, y_temp = train_test_split(X_scaled, y, test_size=0.3, random_state=42)
# Split temporary set into validation (20%) and testing (10%)
X_val, X_test, y_val, y_test = train_test_split(X_temp, y_temp, test_size=1/3, random_state=42)

print("Training set shape:", X_train.shape, y_train.shape)
print("Validation set shape:", X_val.shape, y_val.shape)
print("Testing set shape:", X_test.shape, y_test.shape)

"""8. Training a Decision Tree Model"""

from sklearn.tree import DecisionTreeClassifier, plot_tree
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

dt_classifier = DecisionTreeClassifier(random_state=42)
dt_classifier.fit(X_train, y_train)

y_pred = dt_classifier.predict(X_val)

# Model Evaluation
accu = accuracy_score(y_val, y_pred)
print("Accuracy:", accu)

print(classification_report(y_val, y_pred))

print(confusion_matrix(y_val, y_pred))

print(dt_classifier.get_params())

#Cross-Validation
from sklearn.model_selection import cross_validate , cross_val_score

cv_scores = cross_val_score(dt_classifier, X_encoded, y, cv=5)
print("\nCross-validation Scores:", cv_scores)
print("Mean Cross-validation Score:", np.mean(cv_scores))

y_pred_val = dt_classifier.predict(X_val)

print(y_pred_val)

"""10. Hyperparameter Tuning"""

from sklearn.model_selection import GridSearchCV

param_grid = {
    'max_depth': [None, 5, 10, 20, 30],
    'min_samples_split': [2, 5, 10, 20],
    'min_samples_leaf': [1, 2, 4, 8],
    'criterion': ['gini', 'entropy'],
    'max_features': ['auto', 'sqrt', 'log2']
}

grid_search = GridSearchCV(DecisionTreeClassifier(random_state=42), param_grid, cv=5, scoring='accuracy')
grid_search.fit(X_train, y_train)

print("Best Parameters:", grid_search.best_params_)
print("Best Accuracy:", grid_search.best_score_)

# Train and evaluate the best model
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

accuracy = accuracy_score(y_val, y_pred)
precision = precision_score(y_val, y_pred)
recall = recall_score(y_val, y_pred)
f1 = f1_score(y_val, y_pred)

print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)

from sklearn.model_selection import cross_val_score

# Perform 5-Fold Cross-Validation
cv_scores = cross_val_score(dt_classifier, X, y, cv=5, scoring='accuracy')

# Display cross-validation scores
print("Cross-Validation Scores:", cv_scores)
print("Mean CV Accuracy:", cv_scores.mean())

# Tune hyperparameters
model_tuned = DecisionTreeClassifier(max_depth=5, min_samples_split=10, random_state=42)
model_tuned.fit(X_train, y_train)

# Evaluate the tuned model
y_pred_tuned = model_tuned.predict(X_val)
accuracy_tuned = accuracy_score(y_val, y_pred_tuned)
print("Tuned Model Accuracy:", accuracy_tuned)

from sklearn.ensemble import RandomForestClassifier
rf_classifier = RandomForestClassifier(n_estimators=300, max_depth=20, random_state=42)
rf_classifier.fit(X_train, y_train)
y_pred_rf = rf_classifier.predict(X_val)
print("Random Forest Accuracy:", accuracy_score(y_val, y_pred_rf))

def evaluate_model(model, X_val, y_val):
    y_pred = model.predict(X_val)
    print("Accuracy:", accuracy_score(y_val, y_pred))
    print("Precision:", precision_score(y_val, y_pred))
    print("Recall:", recall_score(y_val, y_pred))
    print("F1 Score:", f1_score(y_val, y_pred))

#decision tree
evaluate_model(model_tuned, X_val, y_val)

#random forest
evaluate_model(rf_classifier, X_val, y_val)